version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cats-nextjs-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: npm run dev
    restart: unless-stopped